### ISSUE TITLE
Allow user based auth?/Console broken

### ISSUE THREAD

**Issue by theMackabu** [Solixity/PteroJS-Panel#1]
Its just a bit weird to have to enter a api key every time.

Console throws a error 403
![image](https://user-images.githubusercontent.com/32078755/118043434-368ada80-b32a-11eb-84ee-a135a4bee356.png)

**Comment by Solixity** [comment]
I haven't touched this is the last few days, I need to though.

I can try adding in user based auth but I'll need a day or two to figure out how to make it exactly work out well.

And about the console, where *exactly* is it breaking at? Some of the functionality isn't 100% stable so I wouldn't advise using this for production if that's your use case.

**Comment by Solixity** [comment]
In substitution of user-based auth (not avoiding it, this would be a "in case this fails" type scenario), I know a package that'll allow for sessions to persist across restarts. Only downsides are:
- You'll need a NoSQL database (mongodb to be exact). If you can't self host one then you can always get a sandbox cluster which gives more than enough disk space for storing less than 2 KB / entity sessions.
- Having too many packages in a node project can possibly slow it down too much and that's the point we'd want to avoid. It's a bit slow as it is already but that's only if you're hosting it on a different network as the panel.

**Comment by theMackabu** [comment]
> I haven't touched this is the last few days, I need to though.
> 
> I can try adding in user based auth but I'll need a day or two to figure out how to make it exactly work out well.
> 
> And about the console, where _exactly_ is it breaking at? Some of the functionality isn't 100% stable so I wouldn't advise using this for production if that's your use case.

Im not using it for production, but console breaks on click, as on load. It is running on the same network as the panel though. This project seems very promising for giving very limited access to a server

**Comment by Solixity** [comment]
> > I haven't touched this is the last few days, I need to though.
> > 
> > I can try adding in user based auth but I'll need a day or two to figure out how to make it exactly work out well.
> > 
> > And about the console, where _exactly_ is it breaking at? Some of the functionality isn't 100% stable so I wouldn't advise using this for production if that's your use case.
> 
> Im not using it for production, but console breaks on click, as on load. It is running on the same network as the panel though. This project seems very promising for giving very limited access to a server

Just tried it on my end, didn't get a 403 but it did start refreshing when it actually shouldn't have so I'll look into that for sure hopefully tonight, if not tomorrow.

And it does give limited access so far. My original plan for this was to have it somewhat easy to navigate and actually even give it more features than the base of Pterodactyl as it is confusing (to me) when I want to add plugins, change the styling and other stuff like that to Pterodactyl so this was made to eliminate those issues + a few others left unknown.

**Comment by Solixity** [comment]
It did just register in my head, what permissions did you give the API Key on the administrator side?

**Comment by Solixity** [comment]
Good news (hopefully), check out [OSMP#dev](https://github.com/Solixity/OpenSourceMinecraftPanel/tree/dev) as that should fix persistent sessions and the console not working. You should be able to switch branches by running `git fetch && git checkout dev` in your preferred shell and then add in `SESSION_DB_URL` to your `.env` file followed by a MongoDB Cluster URL. Again, if you can't self-host then check out [MongoDB Atlas](https://mongodb.com/atlas).

I'll wait for a response before I merge dev with main.

**Comment by theMackabu** [comment]
Ah, I just saw this message now. Ill run the test, hopefully it works!

**Comment by Solixity** [comment]
> Ah, I just saw this message now. Ill run the test, hopefully it works!
> 
> Do you have a discord by any chance?
> 

Yep. If you want to add me on there, my username is Solixity#0001. (Won't be the same tomorrow as that's when my nitro expires haha)

**Comment by theMackabu** [comment]
Ive sent a friend request.

On startup, it successfully loads the site but throws the error

`(node:94594) UnhandledPromiseRejectionWarning: #<Object>
(node:94594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:94594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
